# Generated by Django 5.0.2 on 2024-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
    ]
